### ISSUE TITLE
Release 0.1.0

### ISSUE THREAD

**Issue by oke-aditya** [airctic/icevision#209]
## 🚀 Feature

This might seem a bit early. But we are now almost close to First Release 0.1.0.
We need to follow a release method that will enable us to create a release cycle and properly keep our job done.
This is the method PyTorch follows and is very efficient.
1. Cut a branch for release a week prior, tag it as release/version number this case release/0.1.0. Update the setup.py and setting.ini etc files. This will enable releasing on the new version.
2. Create an issue for release. Tag it as [Release 0.1.0] DO NOT MERGE.
3. Now PRs do not get merged to release branch without approval or cherry-picking. Any further PR to this release must be linked to this Release issue, only then we can think of merging. Only essential and important PRs can be merged. We can Pinup this issue so people know about it.
4. This ensures that the master remains stable and we can keep developing on the master without worrying about the release branch it will stay independent. All CI checks need to be passing on the release branch. No CI failure can be accepted.
5. Finally while releasing, we need to create a PR on release branch with a tag. We need to add a GitHub action for releasing the package.
6. Merge the same the release branch into docker Deploy. It will also deploy the docker image for our repo.
7. Do not delete the release branch. Keep that branch. It can stay for long.

To do before this release once this stuff is done we can close this issue. 

- [ ] Fix the docker deploy action and check it once. Issue #127 
- [x] We need to create proper requirements and configure the settings.ini and setup.py properly. Issue #182.
- [x] Fix up nasty imports which create lot of problems. Issue #181 #184 .
- [ ] Create CI files for Python Package releasing.

Once these are fixed and milestones are reached. We can cut a release branch. And then follow the above steps. 
Note that we need to keep a weeks gap at least when we cut the release branch and actually release it so that we can make last-minute very important fixes.
